---
title: "Features selection using LASSo"
author: "Joshua Edefo"
date: "2024-08-12"
email: "edefojoshua2000@yahoo.com"
output: github_document
---
Install and load the glmnet package if not already installed
```{r a, message=FALSE}

library(glmnet)
library(usethis)

```

Generate a synthetic dataset for demonstration, and Split data

```{r b}
set.seed(123)
n <- 100  # Number of observations
p <- 10   # Number of predictors
X <- matrix(rnorm(n * p), n, p)  # Predictor matrix
beta <- c(3, 0, 0, -2, 0, 0, 1.5, 0, 0, 0)  # True coefficients
y <- X %*% beta + rnorm(n)  # Response vector with noise

# Split data into training and testing sets
train_index <- sample(seq_len(n), size = 0.7 * n)
X_train <- X[train_index, ]
y_train <- y[train_index]
X_test <- X[-train_index, ]
y_test <- y[-train_index]

```

 Fit LASSO model using cross-validation, plot, extract the best lamda value, and make predictions

```{r c}
# Fit LASSO model using cross-validation
lasso_cv <- cv.glmnet(X_train, y_train, alpha = 1, family = "gaussian")

# Plot cross-validation results
plot(lasso_cv)

# Extract the best lambda value
best_lambda <- lasso_cv$lambda.min
best_lambda
cat("Best Lambda: ", best_lambda, "\n")

# Coefficients of the best model
lasso_coef <- coef(lasso_cv, s = "lambda.min")
lasso_coef
print(lasso_coef)
# V1 to V10: These are the coefficients for each feature in the model.
# Represents zero coefficients for the features V5 and V6. In Lasso regression, some coefficients are shrunk to #exactly zero, which helps in feature selection by effectively excluding these variables from the model.

# Make predictions on the test set
predictions <- predict(lasso_cv, s = "lambda.min", newx = X_test)

# Convert the sparse matrix to a regular matrix for easier handling
lasso_coef <- as.matrix(lasso_coef)
lasso_coef

# Identify variables with zero coefficients
zero_coef_vars <- rownames(lasso_coef)[lasso_coef == 0]
zero_coef_vars

#Remove intercept from zero coefficient variables
zero_coef_vars <- zero_coef_vars[zero_coef_vars != "(Intercept)"]
zero_coef_vars

# Remove zero coefficient variables from the dataset
X_reduced <- X[, !(colnames(X) %in% zero_coef_vars)]

```

Evaluate model performance

```{r d}
mse <- mean((y_test - predictions)^2)
cat("Mean Squared Error: ", mse, "\n")
```

session information
```{r f}
sessionInfo()
```
